spring:
  application:
    name: authService
  datasource:
    url: jdbc:mysql://localhost:3306/techoverflow
    username: root
    password: Kota@2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: rohit0060yadav@gmail.com
    password: lvao olqm euzv qzhn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090

jwt:
  secret: mysecretkeymysecretkeymysecretkey
  expiration: 300000
  refresh-expiration: 604800000


